/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Create a new user account with email, password, and profile information.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user
         * @description Authenticate with email and password to receive access and refresh tokens.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Exchange a valid refresh token for a new access token.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout user
         * @description Invalidate the current session. Client should discard tokens.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Retrieve the authenticated user's profile information.
         */
        get: operations["get_current_user_profile_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Schema for user login request.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             * @description User's email address
             */
            email: string;
            /**
             * Password
             * @description User's password
             */
            password: string;
        };
        /**
         * RefreshRequest
         * @description Schema for token refresh request.
         */
        RefreshRequest: {
            /**
             * Refresh Token
             * @description The refresh token to use
             */
            refresh_token: string;
        };
        /**
         * RefreshResponse
         * @description Schema for token refresh response.
         *
         *     Returns a new access token (refresh token is not rotated).
         */
        RefreshResponse: {
            /**
             * Access Token
             * @description New JWT access token
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type (always 'bearer')
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token expiration time in seconds
             */
            expires_in: number;
        };
        /**
         * RegisterRequest
         * @description Schema for user registration request.
         *
         *     Validates email format and enforces password strength requirements.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             * @description User's email address
             */
            email: string;
            /**
             * Password
             * @description User password (8-128 characters, requires uppercase, lowercase, and number)
             */
            password: string;
            /**
             * First Name
             * @description User's first name
             */
            first_name: string;
            /**
             * Last Name
             * @description User's last name
             */
            last_name: string;
            /**
             * @description Type of user account
             * @default client
             */
            user_type: components["schemas"]["UserType"];
        };
        /**
         * TokenResponse
         * @description Schema for authentication token response.
         *
         *     Returned after successful login or token refresh.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description JWT access token
             */
            access_token: string;
            /**
             * Refresh Token
             * @description JWT refresh token
             */
            refresh_token: string;
            /**
             * Token Type
             * @description Token type (always 'bearer')
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token expiration time in seconds
             */
            expires_in: number;
        };
        /**
         * UserResponse
         * @description Schema for user data in API responses.
         *
         *     IMPORTANT: This schema explicitly excludes password_hash.
         *     Never expose password hashes in API responses.
         */
        UserResponse: {
            /**
             * Id
             * @description User's unique identifier (UUID)
             */
            id: string;
            /**
             * Email
             * Format: email
             * @description User's email address
             */
            email: string;
            /**
             * First Name
             * @description User's first name
             */
            first_name: string;
            /**
             * Last Name
             * @description User's last name
             */
            last_name: string;
            /** @description Type of user account */
            user_type: components["schemas"]["UserType"];
            /**
             * Email Verified
             * @description Whether email is verified
             */
            email_verified: boolean;
            /**
             * Is Active
             * @description Whether account is active
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Account creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * UserType
         * @description User type enumeration.
         * @enum {string}
         */
        UserType: "client" | "host" | "both";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_current_user_profile_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
