/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostsIndexRouteImport } from './routes/hosts/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as HostsHostIdRouteImport } from './routes/hosts/$hostId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings/$bookingId'
import { Route as HostsHostIdBookRouteImport } from './routes/hosts/$hostId/book'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIndexRoute = HostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdBookRoute = HostsHostIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => HostsHostIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hosts/$hostId': typeof HostsHostIdRouteWithChildren
  '/bookings/': typeof BookingsIndexRoute
  '/hosts/': typeof HostsIndexRoute
  '/hosts/$hostId/book': typeof HostsHostIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hosts/$hostId': typeof HostsHostIdRouteWithChildren
  '/bookings': typeof BookingsIndexRoute
  '/hosts': typeof HostsIndexRoute
  '/hosts/$hostId/book': typeof HostsHostIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/hosts/$hostId': typeof HostsHostIdRouteWithChildren
  '/bookings/': typeof BookingsIndexRoute
  '/hosts/': typeof HostsIndexRoute
  '/hosts/$hostId/book': typeof HostsHostIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/bookings/$bookingId'
    | '/hosts/$hostId'
    | '/bookings/'
    | '/hosts/'
    | '/hosts/$hostId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/bookings/$bookingId'
    | '/hosts/$hostId'
    | '/bookings'
    | '/hosts'
    | '/hosts/$hostId/book'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/bookings/$bookingId'
    | '/hosts/$hostId'
    | '/bookings/'
    | '/hosts/'
    | '/hosts/$hostId/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  HostsHostIdRoute: typeof HostsHostIdRouteWithChildren
  BookingsIndexRoute: typeof BookingsIndexRoute
  HostsIndexRoute: typeof HostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof HostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/book': {
      id: '/hosts/$hostId/book'
      path: '/book'
      fullPath: '/hosts/$hostId/book'
      preLoaderRoute: typeof HostsHostIdBookRouteImport
      parentRoute: typeof HostsHostIdRoute
    }
  }
}

interface HostsHostIdRouteChildren {
  HostsHostIdBookRoute: typeof HostsHostIdBookRoute
}

const HostsHostIdRouteChildren: HostsHostIdRouteChildren = {
  HostsHostIdBookRoute: HostsHostIdBookRoute,
}

const HostsHostIdRouteWithChildren = HostsHostIdRoute._addFileChildren(
  HostsHostIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  HostsHostIdRoute: HostsHostIdRouteWithChildren,
  BookingsIndexRoute: BookingsIndexRoute,
  HostsIndexRoute: HostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
