/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostsIndexRouteImport } from './routes/hosts/index'
import { Route as HostsHostIdRouteImport } from './routes/hosts/$hostId'
import { Route as HostsHostIdBookRouteImport } from './routes/hosts/$hostId/book'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIndexRoute = HostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdBookRoute = HostsHostIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => HostsHostIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/hosts/$hostId': typeof HostsHostIdRouteWithChildren
  '/hosts/': typeof HostsIndexRoute
  '/hosts/$hostId/book': typeof HostsHostIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/hosts/$hostId': typeof HostsHostIdRouteWithChildren
  '/hosts': typeof HostsIndexRoute
  '/hosts/$hostId/book': typeof HostsHostIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/hosts/$hostId': typeof HostsHostIdRouteWithChildren
  '/hosts/': typeof HostsIndexRoute
  '/hosts/$hostId/book': typeof HostsHostIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/hosts/$hostId'
    | '/hosts/'
    | '/hosts/$hostId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/hosts/$hostId'
    | '/hosts'
    | '/hosts/$hostId/book'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/hosts/$hostId'
    | '/hosts/'
    | '/hosts/$hostId/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  HostsHostIdRoute: typeof HostsHostIdRouteWithChildren
  HostsIndexRoute: typeof HostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof HostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId/book': {
      id: '/hosts/$hostId/book'
      path: '/book'
      fullPath: '/hosts/$hostId/book'
      preLoaderRoute: typeof HostsHostIdBookRouteImport
      parentRoute: typeof HostsHostIdRoute
    }
  }
}

interface HostsHostIdRouteChildren {
  HostsHostIdBookRoute: typeof HostsHostIdBookRoute
}

const HostsHostIdRouteChildren: HostsHostIdRouteChildren = {
  HostsHostIdBookRoute: HostsHostIdBookRoute,
}

const HostsHostIdRouteWithChildren = HostsHostIdRoute._addFileChildren(
  HostsHostIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  HostsHostIdRoute: HostsHostIdRouteWithChildren,
  HostsIndexRoute: HostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
